# Generated by Django 5.2.4 on 2025-07-24 14:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos', regex='^\\+?1?\\d{9,15}$')])),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='CI')),
                ('tipo_vivienda', models.CharField(choices=[('vivienda', 'Vivienda'), ('departamento', 'Departamento')], max_length=15)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('zona', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=200)),
                ('direccion_completa', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('activo', 'Activo')], default='pendiente', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.tiposervicio')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
