# Generated by Django 5.2.4 on 2025-08-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('COD_CATEGORIA', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=100)),
                ('ESTADO_ACTIVO', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseTrabajo',
            fields=[
                ('COD_CLASE', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=30)),
                ('ESTADO_ACTIVO', models.CharField(max_length=1)),
                ('CON_CROQUIS', models.CharField(max_length=1)),
                ('GRUPO', models.CharField(max_length=20)),
                ('MODIFICA_ACCION', models.CharField(max_length=1)),
                ('MODIFICA_FORMA', models.CharField(max_length=1)),
                ('MODIFICA_TARIFA', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('COD_CLIENTE', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=100)),
                ('APELLIDO', models.CharField(max_length=100)),
                ('CI', models.CharField(blank=True, max_length=20, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=100, null=True)),
                ('TELEFONO', models.CharField(blank=True, max_length=15, null=True)),
                ('VIVIENDA', models.CharField(blank=True, max_length=20, null=True)),
                ('PISO', models.CharField(blank=True, max_length=10, null=True)),
                ('CALLE', models.CharField(blank=True, max_length=100, null=True)),
                ('ZONA', models.CharField(blank=True, max_length=100, null=True)),
                ('DIRECCION_COMPLETA', models.CharField(blank=True, max_length=200, null=True)),
                ('NUMERO_PUERTA', models.CharField(blank=True, max_length=20, null=True)),
                ('REFERENCIAS', models.CharField(blank=True, max_length=200, null=True)),
                ('LONGITUD', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('LATITUD', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('TIPO_CLIENTE', models.CharField(blank=True, max_length=10, null=True)),
                ('NIT', models.CharField(blank=True, max_length=20, null=True)),
                ('RAZON_SOCIAL', models.CharField(blank=True, max_length=100, null=True)),
                ('OBSERVACIONES', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('COD_ESTADO', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=100)),
                ('ESTADO', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('COD_FORMA_PAGO', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=30)),
                ('ESTADO_ACTIVO', models.CharField(max_length=1)),
                ('ABREVIACION', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConexion',
            fields=[
                ('COD_TIPO_CONEXION', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=30)),
                ('ESTADO_ACTIVO_TICON', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('COD_TIPO_PAGO', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=30)),
                ('ESTADO_ACTIVO_TIPAG', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('COD_TIPO_PLAN', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=30)),
                ('MONTO_BASICO', models.DecimalField(decimal_places=4, max_digits=10)),
                ('TIPO_BASICO', models.IntegerField()),
                ('F_INICIAL', models.DateField()),
                ('F_FINAL', models.DateField(blank=True, null=True)),
                ('ESTADO_ACTIVO', models.CharField(max_length=1)),
                ('COD_FORMA_PAGO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.formapago')),
                ('COD_TIPO_CONEXION', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.tipoconexion')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('SOLICITUD', models.AutoField(primary_key=True, serialize=False)),
                ('F_SOLICITUD', models.DateField()),
                ('COD_UNIDAD', models.IntegerField()),
                ('NO_EMPLEADO', models.CharField(max_length=6)),
                ('F_PREVISTA', models.DateField(blank=True, null=True)),
                ('OBSERVACIONES', models.CharField(blank=True, max_length=150, null=True)),
                ('F_ESTADO', models.DateField(blank=True, null=True)),
                ('F_ANULACION', models.DateField(blank=True, null=True)),
                ('TIPO_CONEXION', models.CharField(blank=True, max_length=30, null=True)),
                ('F_PREVISTA_VENC', models.DateField(blank=True, null=True)),
                ('COD_FLUJO_ESTADO', models.IntegerField(blank=True, null=True)),
                ('COBERTURA', models.IntegerField(blank=True, null=True)),
                ('COD_CATEGORIA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.categoria')),
                ('COD_CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.cliente')),
                ('COD_ESTADO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.estado')),
                ('COD_FORMA_PAGO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.formapago')),
                ('COD_TIPO_PLAN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.plan')),
                ('COD_TIPO_PAGO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.tipopago')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_INICIO', models.DateField()),
                ('USER_INICIO', models.CharField(max_length=6)),
                ('F_FIN', models.DateField(blank=True, null=True)),
                ('USER_FIN', models.CharField(blank=True, max_length=6, null=True)),
                ('NRO_SEGUIMIENTO', models.IntegerField()),
                ('COD_ESTADO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.estado')),
                ('SOLICITUD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('CONTRATO_INTERNET', models.AutoField(primary_key=True, serialize=False)),
                ('USERNAME', models.CharField(max_length=50)),
                ('CLAVE', models.CharField(max_length=50)),
                ('F_CONTRATO', models.DateField()),
                ('OBSERVACIONES', models.CharField(blank=True, max_length=150, null=True)),
                ('COD_ACCI_CONTRATO', models.IntegerField(blank=True, null=True)),
                ('F_RESCISION', models.DateField(blank=True, null=True)),
                ('F_INSTALACION', models.DateField(blank=True, null=True)),
                ('TIPO_CONEXION', models.CharField(blank=True, max_length=30, null=True)),
                ('ESTADO_FACT', models.IntegerField(blank=True, null=True)),
                ('MODEM', models.CharField(blank=True, max_length=1, null=True)),
                ('COD_CATEGORIA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.categoria')),
                ('COD_CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.cliente')),
                ('COD_ESTADO_CONTRATO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_contrato', to='solicitud.estado')),
                ('COD_ESTADO_SERVICIO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_servicio', to='solicitud.estado')),
                ('COD_FORMA_PAGO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.formapago')),
                ('COD_TIPO_PLAN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.plan')),
                ('F_SOLICITUD', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.solicitud')),
                ('COD_TIPO_PAGO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.tipopago')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('COD_TIPO_TRABAJO', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=30)),
                ('MONTO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COD_MONEDA', models.IntegerField()),
                ('MESESAPLICAR', models.IntegerField()),
                ('INDICADOR_PROCESO', models.CharField(max_length=1)),
                ('GENERA_OT', models.CharField(max_length=1)),
                ('COD_CONCEPTO', models.CharField(max_length=6)),
                ('TRAMITE', models.IntegerField()),
                ('COSTO_FIJO', models.CharField(max_length=1)),
                ('REGULADO', models.CharField(max_length=1)),
                ('COD_CLASE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.clasetrabajo')),
                ('COD_ESTADO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.estado')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='COD_TIPO_TRABAJO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitud.tipotrabajo'),
        ),
    ]
