# Generated by Django 5.2.4 on 2025-07-31 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('abreviacion', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('monto_basico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_basico', models.CharField(max_length=50)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('codigo_item', models.CharField(max_length=20)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.formapago')),
                ('tipo_conexion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.tipoconexion')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ci', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('vivienda', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento')], max_length=20)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('calle', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('direccion_completa', models.TextField()),
                ('numero_puerta', models.CharField(max_length=20)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tipo_cliente', models.CharField(choices=[('COMUN', 'Usuario común'), ('EMPRESA', 'Empresa')], default='COMUN', max_length=10)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cobertura', models.CharField(choices=[('CON_COBERTURA', 'Con cobertura'), ('SIN_COBERTURA', 'Sin cobertura')], default='SIN_COBERTURA', max_length=20)),
                ('estado', models.CharField(choices=[('PEND_COBERTURA', 'Pendiente por cobertura'), ('PEND_EQUIPO', 'Pendiente por equipo'), ('PEND_INSTALACION', 'Pendiente por instalación'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido')], default='PEND_COBERTURA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planes.plan')),
            ],
        ),
    ]
