# Generated by Django 5.2.4 on 2025-08-21 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cod_estado', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Código Estado')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'adsl2_estados',
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_conversion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se convirtió de pre-solicitud a solicitud', null=True, verbose_name='Fecha de Conversión'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_inicio_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha cuando se inició la solicitud', verbose_name='Fecha Inicio Solicitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='solicitud',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número de Solicitud'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('PRE_SOLICITUD', 'Pre-solicitud'), ('SOLICITUD', 'Solicitud')], default='PRE_SOLICITUD', help_text='Indica si es una pre-solicitud o una solicitud formal', max_length=15, verbose_name='Estado de Solicitud'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='adsl2_solicitud',
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('contrato', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Número de Contrato')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Vigencia')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planes.cliente', verbose_name='Solicitud')),
                ('estado_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.estado', verbose_name='Estado Actual')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'adsl2_contrato',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_actual',
            field=models.ForeignKey(blank=True, help_text='Estado actual del proceso (solo aplica cuando es SOLICITUD)', null=True, on_delete=django.db.models.deletion.PROTECT, to='planes.estado', verbose_name='Estado Actual del Proceso'),
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('ot', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Número de OT')),
                ('f_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('f_asignacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('f_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('f_servicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Servicio')),
                ('informe', models.CharField(blank=True, max_length=200, null=True, verbose_name='Informe')),
                ('cod_operario', models.BigIntegerField(blank=True, null=True, verbose_name='Código Operario')),
                ('f_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('cod_unidad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código Unidad')),
                ('cod_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.estado', verbose_name='Estado')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.cliente', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'db_table': 'adsl2_orden_trabajo',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('f_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('nro_seguimiento', models.PositiveIntegerField(verbose_name='Número de Seguimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cod_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.estado', verbose_name='Estado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Seguimiento de Contrato',
                'verbose_name_plural': 'Seguimientos de Contratos',
                'db_table': 'adsl2_seguimiento_contrato',
                'ordering': ['contrato', 'nro_seguimiento'],
                'unique_together': {('contrato', 'nro_seguimiento')},
            },
        ),
        migrations.CreateModel(
            name='SeguimientoOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('f_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('nro_seguimiento', models.PositiveIntegerField(help_text='Orden secuencial de los estados para este cliente', verbose_name='Número de Seguimiento')),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios específicos sobre este cambio de estado', null=True, verbose_name='Observaciones')),
                ('cod_estado', models.ForeignKey(db_column='cod_estado', on_delete=django.db.models.deletion.PROTECT, to='planes.estado', verbose_name='Estado')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.ordentrabajo', verbose_name='Orden de Trabajo')),
                ('solicitud', models.ForeignKey(db_column='solicitud', on_delete=django.db.models.deletion.CASCADE, to='planes.cliente', verbose_name='Solicitud/Cliente')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'db_table': 'adsl2_seguimiento',
                'ordering': ['solicitud', 'nro_seguimiento'],
                'indexes': [models.Index(fields=['solicitud', 'f_inicio'], name='adsl2_segui_solicit_d03968_idx'), models.Index(fields=['cod_estado'], name='adsl2_segui_cod_est_981038_idx')],
                'unique_together': {('solicitud', 'nro_seguimiento')},
            },
        ),
    ]
