# Generated by Django 5.2.4 on 2025-09-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_estado_alter_cliente_options_remove_cliente_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientocontrato',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='seguimientoordentrabajo',
            name='cod_estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado_actual',
        ),
        migrations.RemoveField(
            model_name='seguimientocontrato',
            name='cod_estado',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='cod_estado',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='seguimientoordentrabajo',
            name='orden_trabajo',
        ),
        migrations.AlterUniqueTogether(
            name='seguimientocontrato',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='seguimientoordentrabajo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seguimientoordentrabajo',
            name='solicitud',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_conversion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_inicio_solicitud',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('PEND_COBERTURA', 'Pendiente por cobertura'), ('PEND_EQUIPO', 'Pendiente por equipo'), ('PEND_INSTALACION', 'Pendiente por instalación'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido')], default='PEND_COBERTURA', max_length=20),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='SeguimientoContrato',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='OrdenTrabajo',
        ),
        migrations.DeleteModel(
            name='SeguimientoOrdenTrabajo',
        ),
    ]
