# Generated by Django 5.2.4 on 2025-09-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_remove_seguimientocontrato_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobfactu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_concesion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('factura_interna', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('cod_dosificacion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('contrato', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('periodo_desde', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('periodo_hasta', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('telefono', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('periodo', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cod_mensaje', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('monto_cf', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('numero_renta', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('monto_cotel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('monto_cotel_cf', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('nombre_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc_factura', models.CharField(blank=True, max_length=12, null=True)),
                ('no_autorizacion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('f_limite', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_control', models.CharField(blank=True, max_length=16, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('movimiento', models.CharField(blank=True, max_length=2, null=True)),
                ('f_actualizacion', models.DateField(blank=True, null=True)),
                ('id_transaccion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('estado_transac', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'cobfactu',
                'managed': False,
            },
        ),
    ]
