# Generated by Django 5.2.4 on 2025-09-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CobfactuConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_concesion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('factura_interna', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('cod_dosificacion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('contrato', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('periodo_desde', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('periodo_hasta', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('telefono', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('periodo', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cod_mensaje', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('monto_cf', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('numero_renta', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('monto_cotel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('monto_cotel_cf', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('nombre_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc_factura', models.CharField(blank=True, max_length=12, null=True)),
                ('no_autorizacion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('f_limite', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_control', models.CharField(blank=True, max_length=16, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('movimiento', models.CharField(blank=True, max_length=2, null=True)),
                ('f_actualizacion', models.DateField(blank=True, null=True)),
                ('id_transaccion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('estado_transac', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'cobfactu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CobfactuLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_concesion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('factura_interna', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('cod_dosificacion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('contrato', models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=20, null=True)),
                ('periodo_desde', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('periodo_hasta', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('telefono', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('periodo', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cod_mensaje', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('monto_cf', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('numero_renta', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('monto_cotel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('monto_cotel_cf', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('nombre_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc_factura', models.CharField(blank=True, max_length=12, null=True)),
                ('no_autorizacion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('f_limite', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_control', models.CharField(blank=True, max_length=16, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('movimiento', models.CharField(blank=True, max_length=2, null=True)),
                ('f_actualizacion', models.DateField(blank=True, null=True)),
                ('id_transaccion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('estado_transac', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True)),
                ('migrado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cobfactu_local',
                'indexes': [models.Index(fields=['contrato'], name='cobfactu_lo_contrat_3ff549_idx'), models.Index(fields=['factura_interna'], name='cobfactu_lo_factura_c55556_idx'), models.Index(fields=['fecha_emision'], name='cobfactu_lo_fecha_e_36a113_idx')],
            },
        ),
    ]
