# Generated by Django 5.2.4 on 2025-09-10 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soli', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobfactuconsulta',
            options={'managed': False, 'verbose_name': 'Factura Consulta', 'verbose_name_plural': 'Facturas Consulta'},
        ),
        migrations.AlterModelOptions(
            name='cobfactulocal',
            options={'verbose_name': 'Factura Local', 'verbose_name_plural': 'Facturas Locales'},
        ),
        migrations.RenameField(
            model_name='cobfactulocal',
            old_name='migrado',
            new_name='migrada',
        ),
        migrations.AddField(
            model_name='cobfactulocal',
            name='migrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_migradas', to=settings.AUTH_USER_MODEL, verbose_name='Migrado por'),
        ),
        migrations.AlterField(
            model_name='cobfactulocal',
            name='factura_interna',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cobfactulocal',
            unique_together={('factura_interna', 'contrato')},
        ),
        migrations.AddIndex(
            model_name='cobfactulocal',
            index=models.Index(fields=['fecha_migracion'], name='cobfactu_lo_fecha_m_0cf194_idx'),
        ),
    ]
