# Generated by Django 5.2.4 on 2025-09-12 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soli', '0002_alter_cobfactuconsulta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosClienteConsulta',
            fields=[
                ('contrato', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ampliacion', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_comercial', models.CharField(blank=True, max_length=50, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_acci_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_estado_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('anulado', models.CharField(blank=True, max_length=10, null=True)),
                ('concesion', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_servicio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Servicio Cliente Consulta',
                'verbose_name_plural': 'Servicios Cliente Consulta',
                'db_table': 'servicios_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosClienteLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ampliacion', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_cliente', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('plan_comercial', models.CharField(blank=True, max_length=50, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_acci_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_estado_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('anulado', models.CharField(blank=True, max_length=10, null=True)),
                ('concesion', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True)),
                ('migrada', models.BooleanField(default=True)),
                ('migrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_migrados', to=settings.AUTH_USER_MODEL, verbose_name='Migrado por')),
            ],
            options={
                'verbose_name': 'Servicio Cliente Local',
                'verbose_name_plural': 'Servicios Cliente Locales',
                'db_table': 'servicios_cliente_local',
                'indexes': [models.Index(fields=['contrato'], name='servicios_c_contrat_4d3698_idx'), models.Index(fields=['cod_cliente'], name='servicios_c_cod_cli_f44dc5_idx'), models.Index(fields=['cod_servicio'], name='servicios_c_cod_ser_10a42b_idx'), models.Index(fields=['fecha_migracion'], name='servicios_c_fecha_m_083405_idx')],
                'unique_together': {('contrato', 'cod_cliente')},
            },
        ),
    ]
