# Generated by Django 5.2.4 on 2025-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soli', '0003_serviciosclienteconsulta_serviciosclientelocal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosclientelocal',
            name='anulado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
