# Generated by Django 5.2.4 on 2025-08-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEquipoONU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_asignacion', models.CharField(choices=[('RESERVADO', 'Reservado'), ('ASIGNADO', 'Asignado'), ('DESASIGNADO', 'Desasignado')], default='RESERVADO', max_length=20)),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('equipo_onu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.equipoonu')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud')),
            ],
            options={
                'db_table': 'solicitud_equipo_onu',
                'unique_together': {('solicitud', 'equipo_onu')},
            },
        ),
    ]
