# Generated by Django 5.2.4 on 2025-09-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_solicitudequipoonu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitudequipoonu',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='solicitudequipoonu',
            name='solicitud',
        ),
    ]
